### ISSUE TITLE
Modern media queries

### ISSUE THREAD

**Issue by scriptex** [scriptex/itcss#73]
Introduce media queries for `reduced motion` or dark/light mode.

Example:

```css
@media (prefers-reduced-motion: reduce) {
  * {
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
    scroll-behavior: auto !important;
  }
}
```

More examples and reference: https://developer.mozilla.org/en-US/docs/Web/CSS/@media
